"""Initial migration.

Revision ID: ded0004e86f8
Revises: 
Create Date: 2022-03-23 18:26:45.724926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded0004e86f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_uploaded_file_name', sa.String(length=240), nullable=True),
    sa.Column('uploaded_file_name', sa.String(length=240), nullable=True),
    sa.Column('output_file_path', sa.String(length=240), nullable=True),
    sa.Column('output_file_name', sa.String(length=240), nullable=True),
    sa.Column('begin_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sum', sa.Float(precision=2), nullable=True),
    sa.Column('average', sa.Float(precision=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_files')
    op.drop_table('users')
    # ### end Alembic commands ###
